"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, Pencil, Plus, Search, Settings, Trash2, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import AccountOpenBankingSettings from "./account-open-banking-settings";

type Account = { id: number; name: string; type: string };
type Category = { id: number; name: string };
type FixedExpense = { id: number; accountId: number; name: string; category: string | null; amount: number; payments: Array<{ month: string; transactionId: number }>; skippedMonths: string[] };
type Match = { id: number; date: string; description: string; amount: number; category: string };
const currentMonth = () => new Date().toISOString().slice(0, 7);
const formatDate = (value: string) => new Intl.DateTimeFormat("it-IT", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`));

export default function AccountSettings({ accountId }: { accountId: number }) {
  const [account, setAccount] = useState<Account | null>(null), [categories, setCategories] = useState<Category[]>([]), [expenses, setExpenses] = useState<FixedExpense[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [searchingId, setSearchingId] = useState<number | null>(null), [searchExpense, setSearchExpense] = useState<FixedExpense | null>(null), [matches, setMatches] = useState<Match[]>([]);
  const load = async () => { setLoading(true); const data = await fetch("/api/data").then((response) => response.json()); setAccount((data.accounts || []).find((item: Account) => item.id === accountId) || null); setCategories(data.categories || []); setExpenses((data.fixedExpenses || []).filter((item: FixedExpense) => item.accountId === accountId)); setLoading(false); };
  useEffect(() => { load(); }, [accountId]);
  const post = async (body: Record<string, unknown>) => { const response = await fetch("/api/data", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) setError(data.error || "Operazione non riuscita"); return data; };
  const add = async (name: string, amount: string, category: string) => { const data = await post({ action: "fixed-expense", accountId, name, amount: Number(amount.replace(",", ".")), category }); if (data.error) return false; const match = data.possibleTransactions?.[0]; if (match && confirm(`Il movimento “${match.description}” da € ${Math.abs(match.amount).toFixed(2)} sembra corrispondere. Confermi che questa spesa fissa è già pagata?`)) await post({ action: "fixed-expense-paid", fixedExpenseId: data.row.id, transactionId: match.id }); setError(""); await load(); return true; };
  const editAmount = async (expense: FixedExpense) => { const value = prompt(`Nuovo importo mensile per ${expense.name}`, expense.amount.toFixed(2)); if (value === null) return; await post({ action: "fixed-expense-update", id: expense.id, amount: Number(value.replace(",", ".")) }); await load(); };
  const toggleSkip = async (expense: FixedExpense) => { await post({ action: "fixed-expense-skip", id: expense.id, month: currentMonth() }); await load(); };
  const restoreUnpaid = async (expense: FixedExpense) => { await post({ action: "fixed-expense-unpaid", id: expense.id, month: currentMonth() }); await load(); };
  const searchTransactions = async (expense: FixedExpense) => { setSearchingId(expense.id); setSearchExpense(expense); setMatches([]); const data = await post({ action: "fixed-expense-search", id: expense.id, month: currentMonth() }); if (!data.error) setMatches(data.matches || []); setSearchingId(null); };
  const markPaid = async (transactionId: number) => { if (!searchExpense) return; const data = await post({ action: "fixed-expense-paid", fixedExpenseId: searchExpense.id, transactionId }); if (data.error) return; setSearchExpense(null); setMatches([]); setError(""); await load(); };
  const remove = async (expense: FixedExpense) => { if (!confirm(`Eliminare la spesa fissa “${expense.name}”?`)) return; await fetch("/api/data", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "fixed-expense", id: expense.id }) }); await load(); };

  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><WalletCards size={21}/></span><span>Conti in Chiaro</span></div><nav><a href="/"><ArrowLeft size={15}/> Panoramica</a><a href="/configurazione"><Settings size={15}/> Configurazione</a></nav></aside><section className="content settings-content"><header><div><p className="eyebrow">IMPOSTAZIONI CONTO</p><h1>{account?.name || "Conto"}</h1><p className="page-intro">Gestisci le opzioni specifiche di questo conto.</p></div><Button variant="outline" onClick={() => history.back()}><ArrowLeft size={15}/> Indietro</Button></header>{error && <div className="notice error-notice">{error}</div>}{loading ? <div className="empty">Caricamento…</div> : !account ? <div className="empty">Conto non trovato.</div> : <><AccountOpenBankingSettings accountId={accountId}/><section className="settings-panel fixed-expenses-panel"><div className="settings-heading"><div><h2>Spese fisse mensili</h2><p>Gli importi ancora da pagare vengono riservati nel calcolo del saldo spendibile.</p></div></div>{account.type === "risparmi" ? <p className="fixed-expense-empty">Le spese fisse sono disponibili solo per conti Personale e Spese mese.</p> : <><FixedExpenseForm categories={categories} save={add}/><div className="fixed-expense-list">{expenses.map((expense) => {
    const paid = expense.payments.some((payment) => payment.month === currentMonth()), skipped = expense.skippedMonths?.includes(currentMonth());
    return <article className="fixed-expense-row" key={expense.id}><div className="fixed-expense-main"><strong>{expense.name}</strong><small>{expense.category || "Qualsiasi categoria"}</small></div><strong className="fixed-expense-amount">€ {expense.amount.toFixed(2)}</strong><span className={`fixed-expense-status ${paid ? "paid" : skipped ? "skipped" : "pending"}`}>{paid ? "Pagata" : skipped ? "Saltata" : "Da pagare"}</span><div className="fixed-expense-actions"><button type="button" title="Modifica importo" onClick={() => editAmount(expense)}><Pencil size={15}/></button>{paid && <button type="button" onClick={() => restoreUnpaid(expense)}>Ripristina da pagare</button>}{!paid && skipped && <button type="button" onClick={() => toggleSkip(expense)}>Ripristina</button>}{!paid && !skipped && <><button type="button" onClick={() => searchTransactions(expense)}><Search size={14}/> {searchingId === expense.id ? "Ricerca…" : "Ricerca spesa nel conto"}</button><button type="button" onClick={() => toggleSkip(expense)}>Salta mese</button></>}<button className="danger" title="Elimina" onClick={() => remove(expense)}><Trash2 size={16}/></button></div>{searchExpense?.id === expense.id && <div className="fixed-expense-matches"><div className="fixed-expense-matches-heading"><strong>Movimenti più simili del mese</strong><button type="button" onClick={() => setSearchExpense(null)}>Chiudi</button></div>{searchingId === expense.id ? <p>Ricerca in corso…</p> : matches.length ? matches.map((match) => <div className="fixed-expense-match" key={match.id}><div><strong>{match.description}</strong><small>{formatDate(match.date)} · {match.category}</small></div><strong>€ {Math.abs(match.amount).toFixed(2)}</strong><button type="button" onClick={() => markPaid(match.id)}>Segna come pagata</button></div>) : <p>Nessun movimento compatibile trovato nel mese corrente.</p>}</div>}</article>;
  })}{!expenses.length && <p className="fixed-expense-empty">Nessuna spesa fissa configurata.</p>}</div></>}</section></>}</section></main>;
}

function FixedExpenseForm({ categories, save }: { categories: Category[]; save: (name: string, amount: string, category: string) => Promise<boolean> }) {
  const [name, setName] = useState(""), [amount, setAmount] = useState(""), [category, setCategory] = useState("");
  return <form className="form" onSubmit={async (event) => { event.preventDefault(); if (await save(name, amount, category)) { setName(""); setAmount(""); setCategory(""); } }}><label className="field"><span>Nome</span><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Es. Affitto"/></label><label className="field"><span>Importo previsto</span><input required type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)}/></label><label className="field"><span>Categoria (facoltativa)</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Qualsiasi categoria</option>{categories.map((item) => <option key={item.id}>{item.name}</option>)}</select></label><Button><Plus size={15}/> Aggiungi spesa fissa</Button></form>;
}
