"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, Check, Home, Languages, Landmark, Pencil, Plus, Settings, Trash2, WalletCards, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import EnableBankingSettings from "./enable-banking-settings";
import { normalizeKeyword } from "@/lib/keyword-policy";
import { localeOptions, useLocale } from "@/components/locale-provider";

type Category={id:number;name:string;color:string;keywords:string[]};
type Account={id:number;name:string;color:string;type:"personale"|"risparmi"|"spese_mese"};
type Transaction={accountId:number;amount:number};
const colors=["#d96745","#e9b44c","#4e8d7c","#7c74b5","#db8f74","#b06c49","#9b7b65","#3d7f67","#7b837e","#3279a8"];

export default function CategorySettings(){
  const { locale, setLocale, t } = useLocale();
  const [categories,setCategories]=useState<Category[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[transactions,setTransactions]=useState<Transaction[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[editing,setEditing]=useState<Category|null>(null),[error,setError]=useState(""),[target,setTarget]=useState("all"),[homeAccount,setHomeAccount]=useState("all"),[savingHome,setSavingHome]=useState(false),[homeSaved,setHomeSaved]=useState(false),[busy,setBusy]=useState(false);
  const [blacklists,setBlacklists]=useState({categories:[] as string[],fixedExpenses:[] as string[]});
  const [periodStart,setPeriodStart]=useState(()=>{const date=new Date();date.setDate(date.getDate()-30);return date.toLocaleDateString("sv-SE")}),[periodEnd,setPeriodEnd]=useState(()=>new Date().toLocaleDateString("sv-SE"));
  const load=async()=>{setLoading(true);const d=await fetch("/api/data").then(r=>r.json());setCategories(d.categories||[]);setAccounts(d.accounts||[]);setTransactions(d.transactions||[]);setBlacklists(d.keywordBlacklists||{categories:[],fixedExpenses:[]});setHomeAccount(d.homeAccountId==null?"all":String(d.homeAccountId));setLoading(false)};
  useEffect(()=>{load()},[]);
  const save=async(name:string,color:string,keywords:string[])=>{const body=editing?{action:"category-update",id:editing.id,name,color,keywords}:{action:"category",name,color,keywords};const r=await fetch("/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.error);return}setOpen(false);setEditing(null);setError("");load()};
  const remove=async(c:Category)=>{if(!confirm(`Eliminare la categoria “${c.name}”?`))return;const r=await fetch("/api/data",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"category",id:c.id})});const d=await r.json();if(!r.ok){setError(d.error);return}setError("");load()};
  const danger=async(action:"delete-all"|"delete-period")=>{if(action==="delete-period"&&(!periodStart||!periodEnd||periodStart>periodEnd)){setError("Inserisci un periodo valido: la data iniziale deve precedere quella finale.");return}const label=action==="delete-all"?"CANCELLA TUTTO":"CANCELLA MOVIMENTI";if(prompt(`Operazione irreversibile. Scrivi ${label} per confermare:`)!==label)return;setBusy(true);const r=await fetch("/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,accountId:target,startDate:periodStart,endDate:periodEnd})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Operazione non riuscita");return}setError(action==="delete-all"?"Conti e movimenti cancellati.":`${d.deleted||0} movimenti cancellati dal ${periodStart} al ${periodEnd}.`);load()};
  const saveHomeAccount=async(value:string)=>{setHomeAccount(value);setSavingHome(true);setHomeSaved(false);const r=await fetch("/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"home-account",accountId:value})});const d=await r.json();setSavingHome(false);if(!r.ok){setError(d.error||"Impossibile salvare la preferenza");return}setError("");setHomeSaved(true);setTimeout(()=>setHomeSaved(false),2500)};
  const post=async(body:Record<string,unknown>)=>{const r=await fetch("/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)setError(d.error||"Operazione non riuscita");return d};
  const removeAccount=async(account:Account)=>{if(!confirm(`Eliminare il conto “${account.name}” e tutti i suoi movimenti? Questa operazione non può essere annullata.`))return;const r=await fetch("/api/data",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"account",id:account.id})});const d=await r.json();if(!r.ok){setError(d.error||"Impossibile eliminare il conto");return}setError("");await load()};
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark"><WalletCards size={21}/></span><span>Conti in Chiaro</span></div><nav><a href="/"><ArrowLeft size={15}/> Panoramica</a><a className="active" href="#configurazione"><Settings size={15}/> Configurazione</a><div className="sidebar-submenu" aria-label="Sezioni configurazione"><a href="#conti">I tuoi conti</a><a href="#conto-home">Conto in home</a><a href="#lingua">Lingua</a><a href="#categorie">Categorie</a><a href="#blacklist-categorie">Blacklist categorie</a><a href="#blacklist-spese-fisse">Blacklist spese fisse</a><a href="#enable-banking">Enable Banking</a><a href="#cancellazione-dati">Cancellazione dati</a></div></nav><div className="privacy-note"><span>●</span> Preferenze personali<br/><small>Le modifiche valgono solo per te.</small></div></aside>
    <section className="content settings-content" id="configurazione"><header><a className="mobile-settings-back" href="/"><ArrowLeft size={16}/> Torna alla panoramica</a><div><p className="eyebrow">CONFIGURAZIONE</p><h1>Configurazione generale</h1><p className="page-intro">Gestisci conti, preferenze, categorie e dati personali da un unico spazio.</p></div><Dialog open={open} onOpenChange={v=>{setOpen(v);if(!v){setEditing(null);setError("")}}}><DialogTrigger render={<Button/>}><Plus size={16}/> Nuova categoria</DialogTrigger><DialogContent><DialogHeader><DialogTitle>{editing?"Modifica categoria":"Nuova categoria"}</DialogTitle></DialogHeader><CategoryForm initial={editing} error={error} save={save}/></DialogContent></Dialog></header>
      {error&&!open&&<div className="notice error-notice">{error}<button onClick={()=>setError("")}><X size={15}/></button></div>}
      <section className="settings-panel" id="conti"><div className="settings-heading"><div><h2>I tuoi conti</h2><p>Gestisci i conti, la loro tipologia e aggiungine di nuovi.</p></div></div>
        {loading?<div className="empty">Caricamento…</div>:<div className="accounts settings-accounts">{accounts.map(account=><article className="account account-card" key={account.id}><span style={{background:account.color}}><Landmark size={20}/></span><div><div className="account-title"><small>{account.name}</small><button className="delete-account" aria-label={`Elimina ${account.name}`} onClick={()=>removeAccount(account)}><Trash2 size={14}/></button></div><strong>{new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}).format(transactions.filter(transaction=>transaction.accountId===account.id).reduce((sum,transaction)=>sum+transaction.amount,0))}</strong><select aria-label={`Tipo conto ${account.name}`} value={account.type} onChange={async event=>{await post({action:"account-update",id:account.id,type:event.target.value});await load()}}><option value="personale">Personale</option><option value="risparmi">Risparmi</option><option value="spese_mese">Spese mese</option></select><a className="account-settings-inline" href={`/configurazione/conti/${account.id}`}><Settings size={13}/> Impostazioni conto</a></div></article>)}<Dialog open={accountOpen} onOpenChange={setAccountOpen}><DialogTrigger render={<button className="add-account"/>}><Plus/> Aggiungi conto</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Aggiungi un conto</DialogTitle></DialogHeader><AccountForm post={post} done={async()=>{setAccountOpen(false);await load()}}/></DialogContent></Dialog>{!accounts.length&&<p className="fixed-expense-empty">Nessun conto configurato.</p>}</div>}
      </section>
      <section className="settings-panel home-account-setting" id="conto-home"><div className="settings-heading"><div><h2><Home size={19}/> Conto in home page</h2><p>Scegli il conto da mostrare quando apri la panoramica, oppure visualizzali tutti insieme.</p></div></div><div className="preference-control"><label htmlFor="home-account">Visualizzazione predefinita</label><select id="home-account" value={homeAccount} disabled={loading||savingHome} onChange={e=>saveHomeAccount(e.target.value)}><option value="all">Tutti i conti insieme</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><small aria-live="polite">{savingHome?"Salvataggio…":homeSaved?"Preferenza salvata":"Potrai sempre cambiare conto dalla home page."}</small></div></section>
      <section className="settings-panel language-setting" id="lingua"><div className="settings-heading"><div><h2><Languages size={19}/> {t("language")}</h2><p>{t("languageDescription")}</p></div></div><div className="language-options" role="radiogroup" aria-label={t("language")}>{localeOptions.map(option=><button type="button" role="radio" aria-checked={locale===option.code} className={locale===option.code?"active":""} key={option.code} onClick={()=>setLocale(option.code)}><span aria-hidden="true">{option.flag}</span><strong>{option.name}</strong>{locale===option.code&&<Check size={17}/>}</button>)}</div></section>
      <section className="settings-panel" id="categorie"><div className="settings-heading"><div><h2>Le tue categorie</h2><p>{categories.length} categorie disponibili durante l’inserimento e l’importazione.</p></div></div>
        {loading?<div className="empty">Caricamento…</div>:<div className="category-list">{categories.map(c=><article className="category-row" key={c.id}><span className="category-swatch" style={{background:c.color}}/><div><strong>{c.name}</strong><small>{c.keywords?.length?`${c.keywords.length} parole chiave`:"Nessuna parola chiave"}</small><div className="keyword-preview">{(c.keywords||[]).slice(0,5).map(keyword=><span key={keyword}>{keyword}</span>)}{c.keywords?.length>5&&<span>+{c.keywords.length-5}</span>}</div></div><div className="row-actions"><button aria-label={`Modifica ${c.name}`} onClick={()=>{setEditing(c);setOpen(true)}}><Pencil size={16}/></button><button className="danger" aria-label={`Elimina ${c.name}`} onClick={()=>remove(c)}><Trash2 size={16}/></button></div></article>)}</div>}
      </section>
      <KeywordBlacklistPanel id="blacklist-categorie" title="Black list parole chiave categorie" description="Queste parole non vengono usate per assegnare automaticamente le categorie." scope="category" keywords={blacklists.categories} loading={loading} post={post} reload={load}/>
      <KeywordBlacklistPanel id="blacklist-spese-fisse" title="Black list parole chiave spese fisse" description="Queste parole non vengono usate per associare automaticamente le spese fisse." scope="fixed_expense" keywords={blacklists.fixedExpenses} loading={loading} post={post} reload={load}/>
      <div className="settings-tip"><Check size={18}/><p><b>Le modifiche sono immediate.</b><br/>Se rinomini una categoria, aggiorniamo anche tutti i movimenti già associati.</p></div>
      <EnableBankingSettings />
      <section className="settings-panel danger-zone" id="cancellazione-dati"><div className="settings-heading"><div><p className="eyebrow">AREA PERICOLOSA</p><h2>Cancellazione dati</h2><p>Queste operazioni sono definitive e richiedono una conferma scritta.</p></div></div>
        <div className="danger-action"><div><b>Cancella movimenti</b><p>Scegli il conto e il periodo da cancellare. Sono incluse entrambe le date.</p></div><div className="danger-controls period-controls"><select aria-label="Conto da cui cancellare i movimenti" value={target} onChange={e=>setTarget(e.target.value)}><option value="all">Tutti i conti</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><label><span>Dal</span><input type="date" value={periodStart} max={periodEnd||undefined} onChange={e=>setPeriodStart(e.target.value)}/></label><label><span>Al</span><input type="date" value={periodEnd} min={periodStart||undefined} onChange={e=>setPeriodEnd(e.target.value)}/></label><Button variant="outline" disabled={busy||!accounts.length||!periodStart||!periodEnd||periodStart>periodEnd} onClick={()=>danger("delete-period")}><Trash2 size={15}/> Cancella movimenti</Button></div></div>
        <div className="danger-action critical"><div><b><AlertTriangle size={16}/> Cancella tutto</b><p>Elimina tutti i conti, i movimenti e i budget. Le categorie restano disponibili.</p></div><Button disabled={busy||!accounts.length} onClick={()=>danger("delete-all")}><Trash2 size={15}/> Cancella tutto</Button></div>
      </section>
    </section>
  </main>
}

function CategoryForm({initial,error,save}:{initial:Category|null,error:string,save:(n:string,c:string,k:string[])=>void}){
  const [name,setName]=useState(initial?.name||""),[color,setColor]=useState(initial?.color||colors[2]),[keywords,setKeywords]=useState<string[]>(initial?.keywords||[]),[keyword,setKeyword]=useState("");
  const addKeyword=()=>{const value=normalizeKeyword(keyword);if(value&&!keywords.includes(value))setKeywords([...keywords,value]);setKeyword("")};
  return <form className="form" onSubmit={e=>{e.preventDefault();const pending=normalizeKeyword(keyword);save(name,color,pending&&!keywords.includes(pending)?[...keywords,pending]:keywords)}}><label className="field"><span>Nome</span><input autoFocus required maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="Es. Animali"/></label><fieldset className="keyword-field"><legend>Parole chiave</legend><p>Se la descrizione contiene una di queste parole, verrà proposta questa categoria.</p><div className="keyword-editor"><input value={keyword} maxLength={40} onChange={e=>setKeyword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addKeyword()}}} placeholder="Es. supermercato"/><Button type="button" variant="outline" onClick={addKeyword}>Aggiungi</Button></div><div className="keyword-list">{keywords.map(value=><span key={value}>{value}<button type="button" aria-label={`Rimuovi ${value}`} onClick={()=>setKeywords(keywords.filter(item=>item!==value))}><X size={12}/></button></span>)}{!keywords.length&&<small>Nessuna parola chiave impostata.</small>}</div></fieldset><fieldset className="color-field"><legend>Colore</legend><div>{colors.map(c=><button type="button" key={c} onClick={()=>setColor(c)} style={{background:c}} className={color===c?"selected":""} aria-label={`Colore ${c}`}>{color===c&&<Check size={15}/>}</button>)}<label className="custom-color"><input type="color" value={color} onChange={e=>setColor(e.target.value)}/><span>Personalizzato</span></label></div></fieldset>{error&&<p className="error">{error}</p>}<Button>{initial?"Salva modifiche":"Crea categoria"}</Button></form>
}

function KeywordBlacklistPanel({id,title,description,scope,keywords,loading,post,reload}:{id:string;title:string;description:string;scope:"category"|"fixed_expense";keywords:string[];loading:boolean;post:(body:Record<string,unknown>)=>Promise<any>;reload:()=>Promise<void>}){
  const [keyword,setKeyword]=useState(""),[saving,setSaving]=useState(false);
  const add=async()=>{const value=normalizeKeyword(keyword);if(!value)return;setSaving(true);const result=await post({action:"keyword-blacklist-add",scope,keyword:value});setSaving(false);if(!result.error){setKeyword("");await reload()}};
  const remove=async(value:string)=>{if(!confirm(`Rimuovere “${value}” dalla blacklist?`))return;const result=await post({action:"keyword-blacklist-remove",scope,keyword:value});if(!result.error)await reload()};
  return <section className="settings-panel keyword-blacklist-panel" id={id}><div className="settings-heading"><div><h2>{title}</h2><p>{description}</p></div></div><div className="keyword-editor"><input value={keyword} onChange={event=>setKeyword(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();add()}}} placeholder="Aggiungi parola chiave"/><Button type="button" onClick={add} disabled={saving||!keyword.trim()}><Plus size={14}/> {saving?"Salvataggio…":"Aggiungi"}</Button></div>{loading?<div className="empty">Caricamento…</div>:<div className="keyword-list blacklist-keyword-list">{keywords.map(value=><span key={value}>{value}<button type="button" aria-label={`Rimuovi ${value} dalla blacklist`} onClick={()=>remove(value)}><X size={13}/></button></span>)}{!keywords.length&&<small>Nessuna parola chiave in blacklist.</small>}</div>}</section>;
}

function AccountForm({post,done}:{post:(body:Record<string,unknown>)=>Promise<any>;done:()=>Promise<void>}){
  const [name,setName]=useState(""),[type,setType]=useState("personale"),[saving,setSaving]=useState(false);
  return <form className="form" onSubmit={async event=>{event.preventDefault();setSaving(true);const result=await post({action:"account",name,type});setSaving(false);if(!result.error)await done()}}><label className="field"><span>Nome del conto</span><input autoFocus required value={name} onChange={event=>setName(event.target.value)} placeholder="Es. Conto principale"/></label><label className="field"><span>Tipologia</span><select value={type} onChange={event=>setType(event.target.value)}><option value="personale">Personale</option><option value="risparmi">Risparmi</option><option value="spese_mese">Spese mese</option></select></label><Button disabled={saving}>{saving?"Salvataggio…":"Aggiungi conto"}</Button></form>;
}
