"use client";

import { useEffect, useState } from "react";
import { Check, ChevronDown, FileKey2, KeyRound, ShieldCheck, Power, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ENABLE_BANKING_REDIRECT_URL, PRIVACY_URL, TERMS_URL } from "@/lib/open-banking-urls";

type Config = { configured: boolean; applicationId?: string; privateKeyConfigured: boolean; status: "NOT_CONFIGURED" | "CONFIGURED" | "VALID" | "ERROR" };

export default function EnableBankingSettings() {
  const [config, setConfig] = useState<Config | null>(null), [applicationId, setApplicationId] = useState(""), [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const load = async () => { const response = await fetch("/api/open-banking/enable-banking"); setConfig(await response.json()); };
  useEffect(() => { load(); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!file) return; setBusy(true); setMessage(""); const body = new FormData(); body.set("applicationId", applicationId); body.set("privateKey", file); const response = await fetch("/api/open-banking/enable-banking", { method: "POST", body }); const data = await response.json(); setBusy(false); if (!response.ok) return setMessage(data.error || "Salvataggio non riuscito"); setFile(null); setApplicationId(""); setConfig(data); setMessage("Configurazione salvata in modo sicuro."); };
  const verify = async () => { setBusy(true); setMessage(""); const response = await fetch("/api/open-banking/enable-banking", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "verify" }) }); const data = await response.json(); setBusy(false); setMessage(response.ok ? "Configurazione verificata con Enable Banking." : data.error); await load(); };
  const disable = async () => { if (!confirm("Disabilitare Enable Banking? Verranno eliminati la configurazione, la private key cifrata, le autorizzazioni e tutti i collegamenti bancari. I movimenti già importati resteranno disponibili.")) return; setBusy(true); setMessage(""); const response = await fetch("/api/open-banking/enable-banking", { method: "DELETE" }); const data = await response.json(); setBusy(false); if (!response.ok) return setMessage(data.error || "Disattivazione non riuscita"); setConfig({ configured: false, privateKeyConfigured: false, status: "NOT_CONFIGURED" }); setMessage("Enable Banking disabilitato. Ora puoi caricare una nuova configurazione."); };
  return <section className="settings-panel enable-banking-setting" id="enable-banking"><div className="settings-heading"><div><h2><ShieldCheck size={20}/> Enable Banking</h2><p>Collega in modo sicuro le credenziali della tua applicazione.</p></div>{config?.configured && <span className={`integration-status status-${config.status.toLowerCase()}`}>{config.status === "VALID" ? "Verificata" : config.status === "ERROR" ? "Errore" : "Configurata"}</span>}</div>
    <div className="enable-banking-prerequisites"><p>Prima di procedere alla configurazione, bisogna configurare correttamente l’account Enable Banking.</p><details><summary>Guida alla configurazione <ChevronDown size={16}/></summary><ol><li>Accedi al Control Panel Enable Banking e crea l’applicazione.</li><li>Configura nell’applicazione gli URL indicati qui sotto e abilita l’accesso alle banche che vuoi collegare.</li><li>Conserva l’Application ID e la private key PEM PKCS#8 generata: inseriscili qui e verifica la configurazione.</li><li>Apri le impostazioni di ciascun conto, scegli la banca e completa l’autorizzazione.</li></ol></details></div>
    <div className="integration-urls"><p>Configura questi indirizzi nel pannello Enable Banking:</p><dl><div><dt>Redirect URL</dt><dd><a href={ENABLE_BANKING_REDIRECT_URL}>{ENABLE_BANKING_REDIRECT_URL}</a></dd></div><div><dt>Privacy URL</dt><dd><a href={PRIVACY_URL}>{PRIVACY_URL}</a></dd></div><div><dt>Terms URL</dt><dd><a href={TERMS_URL}>{TERMS_URL}</a></dd></div></dl></div>
    {!config ? <div className="empty">Caricamento…</div> : config.configured ? <div className="integration-summary"><dl><div><dt>Application ID</dt><dd>{config.applicationId}</dd></div><div><dt>Private Key</dt><dd><Check size={16}/> Configurata</dd></div></dl><p className="security-hint"><KeyRound size={15}/> La private key è cifrata e non verrà mai più mostrata. Per caricare credenziali diverse devi prima disabilitare Enable Banking.</p><div className="integration-actions"><Button variant="outline" disabled={busy} onClick={verify}><ShieldCheck size={15}/> Verifica configurazione</Button><Button variant="outline" disabled={busy} onClick={disable}><Power size={15}/> {busy ? "Disattivazione…" : "Disabilita Enable Banking"}</Button></div></div> : <form className="integration-form" onSubmit={save}><div className="integration-form-copy"><strong>Credenziali dell’applicazione</strong><p>Inserisci i dati generati nel pannello Enable Banking. Potrai modificarli solo dopo aver disabilitato l’integrazione.</p></div><label className="field integration-id-field"><span>Application ID</span><div className="integration-input-wrap"><ShieldCheck size={18}/><input required value={applicationId} onChange={event => setApplicationId(event.target.value)} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" autoComplete="off" spellCheck={false}/></div><small>L’identificativo UUID assegnato alla tua applicazione.</small></label><label className={`field pem-upload${file ? " has-file" : ""}`}><span>Private Key</span><input required type="file" accept=".pem,application/x-pem-file" onChange={event => setFile(event.target.files?.[0] || null)}/><span className="pem-upload-box"><span className="pem-upload-icon">{file ? <Check size={22}/> : <FileKey2 size={22}/>}</span><span><strong>{file ? file.name : "Seleziona il file .pem"}</strong><small>{file ? `${Math.max(1, Math.ceil(file.size / 1024))} KB · pronto per il caricamento` : "Fai clic per scegliere la private key PKCS#8"}</small></span><span className="pem-upload-action">{file ? "Cambia file" : "Sfoglia"}</span></span><small>La chiave verrà cifrata immediatamente e non sarà mai più mostrata.</small></label><div className="integration-form-footer"><span><KeyRound size={15}/> Cifratura AES-256-GCM</span><Button disabled={busy || !file || !applicationId.trim()}><Upload size={15}/>{busy ? "Salvataggio…" : "Salva configurazione"}</Button></div></form>}
    {message && <p className="integration-message" role="status">{message}</p>}
  </section>;
}
